      - name: Set up Vulkan environment
        run: |
          echo "export VULKAN_SDK=/usr/include/vulkan" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
