name: Build for ARMv7

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvulkan-dev gcc-arm-linux-gnueabi g++-arm-linux-gnueabi make

      - name: Check toolchain file
        run: |
          ls -l toolchains/armv7.toolchain.cmake  # Verifica se o arquivo existe

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ../src -DCMAKE_TOOLCHAIN_FILE=../toolchains/armv7.toolchain.cmake

      - name: Build
        run: |
          cd build
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Use uma versão estável da ação
        with:
          name: waifu2x-ncnn-vulkan-armv7
          path: build/waifu2x-ncnn-vulkan-armv7.tar.gz  # Ajuste o caminho conforme necessário
