name: Build for ARMv7

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libvulkan-dev gcc-arm-linux-gnueabi g++-arm-linux-gnueabi make

      - name: Set up Vulkan environment
        run: |
          echo "export VULKAN_SDK=/usr/include/vulkan" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Create toolchain directory
        run: |
          mkdir -p toolchains  # Cria o diretório toolchains se não existir

      - name: Create toolchain file
        run: |
          echo "SET(CMAKE_SYSTEM_NAME Linux)" > toolchains/armv7.toolchain.cmake
          echo "SET(CMAKE_SYSTEM_PROCESSOR arm)" >> toolchains/armv7.toolchain.cmake
          echo "SET(CMAKE_C_COMPILER arm-linux-gnueabi-gcc)" >> toolchains/armv7.toolchain.cmake
          echo "SET(CMAKE_CXX_COMPILER arm-linux-gnueabi-g++)" >> toolchains/armv7.toolchain.cmake

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ../src -DCMAKE_TOOLCHAIN_FILE=../toolchains/armv7.toolchain.cmake

      - name: Build
        run: |
          cd build
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Use uma versão estável da ação
        with:
          name: waifu2x-ncnn-vulkan-armv7
          path: build/waifu2x-ncnn-vulkan-armv7.tar.gz  # Ajuste o caminho conforme necessário
